### PR TITLE
Optimize repository size

### PR DESCRIPTION
**Pull request by Teraskull**
This PR contains the following changes:

* Reduce the overall JS library size from `110mb` to only `3mb`.
* Delete unused JS libraries from the git history using [bfg](https://github.com/rtyley/bfg-repo-cleaner/). (That is the reason the commits in this PR are old.)
* Remove unused CSS and JS imports.
* Update title name and favicon of the web interface.
* Make sidebar fixed.
* Trim white-space in JS files.
* Fix "colorpicker is not a function" error in the browser console.
* Fix "too high" popup with a valid frequency in the General Settings.
* Update effect icons, to support Font-Awesome 5 and to look more suitable.
* Save `config.json` to `/share/.mlsc`, to easily restore settings, and to avoid `git pull` issues when the `config.json` is modified. 

I have no idea if we will be able to merge this without problems, it's the first time I am using a git history cleaner. But it is worth it since the repo size is now around `35mb` instead of the previous `140mb`.

I also tested everything, didn't get any issues after removing most libraries.

### CODE REVIEW

**Comment by TobKra96** [comment]
This doesn't seem to be right. It looks like, the PR tries to commit all existing commits again.
If I try to merge it, the repository won't reset, it will try to add all the commits.
What do you mean?

**Comment by Teraskull** [comment]
Hm, I was hoping it will force override the old commits. Can you try experimenting with it? Try deleting everything in your repo and then manually copying my repo and force pushing. There is no other way to remove the commits with unused libraries.

**Comment by TobKra96** [comment]
Ok, I will start with the experiments tomorrow.

**Comment by TobKra96** [comment]
Hi, can you check https://github.com/TobKra96/music_led_strip_control/tree/clean_git_history

I created a new branch with the `git checkout --orphan <name_you_choose_for_orphan_branch>` command.
Merged your master into it and commit it.

I will replace the master with this branch if everything is good.

**Comment by Teraskull** [comment]
Good idea, I should have used branches before, to make sure `master` is stable.

**Comment by TobKra96** [comment]
Do you think the changes are stable? Or should we work with the `clean_git_history` branch until it is stable and replace the master with it?
So you can try to make a pull request to the `clean_git_history` branch?

**Comment by Teraskull** [comment]
I believe these changes are stable enough. You can replace `master`, but don't delete it , just rename. After this PR we will work on the `clean_git_history` branch.

**Comment by TobKra96** [comment]
Ok, I will replace the baster with the `clean_git_history` and start a new branch called `dev_2.1` for our new changes/bugfixes.
You can do pull requests on this branch. If it is stable, we can merge it to the master.

**Comment by Teraskull** [comment]
good, you can proceed.

**Comment by TobKra96** [comment]
`master` renamed to `master_old`. `clean_git_history` renamed to `master`.
`master` set to default. `dev_2.1` created from `master`.

**Comment by Teraskull** [comment]
Great, can you pull my last commits to `master` before I can switch to `dev_2.1`?

**Comment by TobKra96** [comment]
Done. Everything is merged and up to date.

**Pull request closed without merging**
