### PR TITLE
Clean up the codebase

### PR DESCRIPTION
**Pull request by Teraskull**
This PR contains the following changes:

* Add `setup.sh`, to simplify the installation process.
* Update `.gitignore` to ignore more Python file types.
* Format the whole Python codebase using PEP8 style.
* Format `custom.css` using a CSS formatter.
* Format and sort alphabetically both `config.json` and `config.json.bak` using a JSON formatter.
* Change the default webserver port to `8080`, in case another service is running on the port `80` already.
* Rename `Light Blue` to `Cyan`, in order to follow the correct color naming scheme.
* Fix a few typos in comments and strings.
* Make all code comments and docstrings more consistent across the codebase.
* Trim white-space.
* Update `README.md` to make it more visually appealing.

### CODE REVIEW

**Comment by Teraskull** [comment]
`TODO:`

* Rename all instances of `colour` to `color`.
* Refactor most strings to f-strings.
* Refactor `super()` functions.
* Refactor repeating code into functions.

**Comment by TobKra96** [comment]
Hi, great work. I will check the changes and do some tests now.
Do you see a big benefit to change the default port to 8080?

**Comment by TobKra96** [comment]
Hi, i saw some problems with the setup.sh installation:

```
Processing triggers for libc-bin (2.28-10+rpi1) ...

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --yes

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --yes

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --yes

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --yes

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --yes

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --yes
Cloning into 'music_led_strip_control'...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (143/143), done.
remote: Total 6007 (delta 65), reused 83 (delta 2), pack-reused 5859
Receiving objects: 100% (6007/6007), 20.11 MiB | 8.98 MiB/s, done.
Resolving deltas: 100% (1844/1844), done.
Checking out files: 100% (4967/4967), done.
sh: 51: cannot create /etc/asound.conf: Permission denied
MLSC installation is done. Please reboot your system (sudo reboot).

```

I think we have to change the --yes command option to `--no-input`.

`sh: 51: cannot create /etc/asound.conf: Permission denied`
I think we should force the sudo with:
`curl -sSL https://raw.githubusercontent.com/TobKra96/music_led_strip_control/master/setup.sh | sudo sh`

If I try to restart the installation, it will show the following error:

```
fatal: destination path 'music_led_strip_control' already exists and is not an empty directory.
```
Should we delete the repo folder before. Or check if it exists and tries a pull?
What do you mean?

Have a great day!

**Comment by Teraskull** [comment]
Regarding the port 8080, yes, because most people are already hosting Pi Hole or Adguard Home, and they are on port 80. However, we can still change it to 80 in the General Settings if we want to.

Regarding the setup script, it is completely untested, so I am still working on it.

**Comment by TobKra96** [comment]
Ok, I understand. Port 8080 is fine for me. I will change the documentation after merge the pull request.
Can you give me a trigger, if the setup script is finished?
After the trigger, I will test the script and merge the pull request.

Thank you for your efforts.
Have a great day!

**Comment by Teraskull** [comment]
Of course, I am testing everything to make sure nothing is broken, and will let you know when it is ready to merge.

No problem, I really enjoy this project, you did good work!

**Comment by Teraskull** [comment]
@TobKra96, the setup script works well now, can you test it?

**Comment by TobKra96** [comment]
Hi,
I tried the setup script. The first installation works without problems.
If I restart the script, the following error appears:
```
Packages updated and installed.

[2/3] Installing MLSC...
Skipped.

[3/3] Configuring microphone settings...

Backup of existing /etc/asound.conf created.
sh: 158: Syntax error: "(" unexpected

```

**Comment by Teraskull** [comment]
Hmm, that's strange, didn't happen to me after a few tests. I will check this issue.

**Comment by TobKra96** [comment]
I used the following command: `curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo sh`

**Comment by Teraskull** [comment]
Can you try with:

```bash
curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo /bin/sh
```

I think this might be the issue, when it overrides sh with bash.

**Comment by TobKra96** [comment]
I tried `curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo /bin/sh`.
The same error appears.
Same with https://github.com/TobKra96/music_led_strip_control/pull/54/commits/8b3a2db76c6fbef61eaf16330d609c01293577ba

**Comment by TobKra96** [comment]
With `curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo /bin/bash` the syntax error disappears, but the sh function like the color does not work.

**Comment by Teraskull** [comment]
We need to find the correct and consistent way to run the setup.

**Comment by Teraskull** [comment]
What about:

```bash
curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo /usr/bin/sh
```

**Comment by TobKra96** [comment]
No success with `curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo /usr/bin/sh`
same error.
I downloaded the script now with `curl https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh > setup.sh` and executed it with `sudo sh setup.sh`. The script does not show the systax error.

With the downloaded version, I also got the confirm dialog. With the "single" command the confirm dialog does not appear.

**Comment by Teraskull** [comment]
The issue is because the script is written in bash, and we are trying to execute it in sh. I am rewriting the script to support sh.

**Comment by Teraskull** [comment]
@TobKra96 should be working with:

```bash
curl -sSL https://raw.githubusercontent.com/Teraskull/music_led_strip_control/master/setup.sh | sudo bash
```

**Comment by TobKra96** [comment]
Yes it worked.
Just one more small error:
```
[2/3] Installing MLSC...
MLSC is already installed. Do you want to reinstall it? [y/N] y
Proceeding...
mv: cannot move 'music_led_strip_control' to 'music_led_strip_control_bak/music_led_strip_control': Directory not empty

Backup of MLSC created.
fatal: destination path 'music_led_strip_control' already exists and is not an empty directory.

```

**Comment by Teraskull** [comment]
OH, now there is a duplicate error. Great. Time to fix that one.

**Comment by Teraskull** [comment]
I believe there is an error on your side. Why is the directory inside the backup?

```
'music_led_strip_control_bak/music_led_strip_control'
```
`music_led_strip_control` should get renamed to `music_led_strip_control_bak`, not moved into it.

Can you delete the `/share` folder and try again?

**Comment by TobKra96** [comment]
ok, nevermind. It was an error, that was caused by one of the failed script executions before.
I deleted /share and everything works three times in a row. :-)

Is the pull request ready for my review?
I would start with the review and edit the installation guide tomorrow. 

Have a great Sunday evening.

**Comment by Teraskull** [comment]
One small correction, I am modifying the setup script to delete the previous backup, to make sure it always renames correctly. After the test, you can merge.

**Comment by Teraskull** [comment]
Okay, everything seems alright, you can now do a clean test of the setup script, and merge the PR.

**Comment by TobKra96** [comment]
Hi,
I like the new web interface mockup. It's fancier than mine before.
Some ideas for the scheme. One of the wires (Raspberry Pi, Power Supply Gnd) is not parallel. I know it's just a small thing, but you can notice it. 
I am not sure if we should use real pictures or draw. Maybe we should redesign the existing ones.
Here is the PowerPoint with the schematics:
[MLSC.pptx](https://github.com/TobKra96/music_led_strip_control/files/5942075/MLSC.pptx)

What do you mean? Do you like the schematics with real pictures more than the draws?

Have a great day!

**Comment by Teraskull** [comment]
I feel like real images are more appealing and understandable for the end user. I will redo the wires. I also don't like that they are not paralel. It is a good idea to add a real connection schematic, but in the wiki.

Do you mind if I redesign the logo for MLSC? I believe it should have a clean logo to make the whole product more professional. I will open an issue, where I will show you different logo options, and you can select the best one.

**Comment by TobKra96** [comment]
Ok, I am open for new designs.
An additional hint: The signal cable of the esp is connected to the do pin and not the di pin.

For the logo I would reuse the color theme of the webinterface to get a harmonic design. Maybe we can use the color theme for the schematics too.

**Review by TobKra96 — APPROVED** [review]

**Pull request merged**
